### ISSUE TITLE
multiple tvs?

### ISSUE THREAD

**Issue by Travisco29** [JarekToro/homebridge-roku-tv#1]
only one will show up in homekit with this plugin?

**Comment by JarekToro** [comment]
Correct. That is the current implementation, the accessories need To be published external to support multiple TVs. Should be an easy fix perhaps over the weekend I can work on it.

**Comment by MikeDProducer** [comment]
That would be great to control multiple TVs. This plugin is fantastic. Brilliant work!

**Comment by Travisco29** [comment]
any progress on it? ;)

**Comment by JarekToro** [comment]
I don't have multiple TVs to test if it is working. Im happy to accept a TV as a donation ;) lol or you can give it a test as well.

**Comment by JarekToro** [comment]
Potential Fix is live Version 1.0.6

**Comment by itsethamphetamine** [comment]
In homebridge, both of my TVs are found, but there appears to be a collision issue, so only one will be transferred to HomeKit as a device, and only one shows in the accessory pane as well. Here is the loading errors I get. Happy to provide anything else to add to this plugin's success:

`[5/25/2020, 20:18:58] [RokuTV] Roku Tv Ip is: http://192.168.7.222:8060
[5/25/2020, 20:18:58] [RokuTV] Adding Input FandangoNOW Movies & TV with info ID: 48607027, TYPE: menu
[5/25/2020, 20:18:58] [RokuTV] Adding Input HDMI 1 (ARC) with info ID: 1295095987, TYPE: tvin
[5/25/2020, 20:18:58] [RokuTV] Adding Input Nintendo Switch with info ID: 1295095989, TYPE: tvin
[5/25/2020, 20:18:58] [RokuTV] Adding Input Computer with info ID: 1295095988, TYPE: tvin
[5/25/2020, 20:18:58] [RokuTV] Adding Input Home with info ID: 1450575459, TYPE: Home
[5/25/2020, 20:18:58] [RokuTV] Roku Tv Ip is: http://192.168.7.55:8060
[5/25/2020, 20:18:58] [RokuTV] Adding Input FandangoNOW Movies & TV with info ID: 48607027, TYPE: menu
[5/25/2020, 20:18:58] [RokuTV] Adding Input HDMI 3 (ARC) with info ID: 1295095989, TYPE: tvin
[5/25/2020, 20:18:58] [RokuTV] Adding Input AppleTV with info ID: 1295095987, TYPE: tvin
[5/25/2020, 20:18:58] [RokuTV] Adding Input Home with info ID: 1450575459, TYPE: Home
[5/25/2020, 20:18:58] [RokuTV] Error: Accessory Office TV experienced an address collision.
    at /usr/local/lib/node_modules/homebridge/src/server.ts:574:15
    at Array.forEach (<anonymous>)
    at Server.handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:554:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.publishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:302:10)
    at RokuTvPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-roku-tv-plugin/src/roku-tv-platform.ts:78:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[5/25/2020, 20:18:58] Office TV is running on port 44225.
[5/25/2020, 20:18:58] Please add [Office TV] manually in Home app. Setup Code: 100-10-100`

**Comment by JarekToro** [comment]
Are the rokus named the same?

**Comment by JarekToro** [comment]
@itsethamphetamine An update was added that fixed some registration issues on the platform. Im not sure but the issues may be related. It might be worth updating and testing it out again.

**Comment by itsethamphetamine** [comment]
@JarekToro, updated to 1.0.8, and the address collision still happens. 
What is odd, is that the original TV it found (Office) is no longer listed as a device, and the one that has the collision is now listed and shows in HomeKit.

**Comment by sandcheeeez** [comment]
Hi @JarekToro thank you for all your work so far in getting this working. I successfully added one Roku Express to the home app but received the same error as @itsethamphetamine (see below)

If I can provide any additional logs that might help with troubleshooting this please let me know and I will do so promptly.


[5/28/2020, 21:09:31] [RokuTV] Error: Accessory Loft experienced an address collision.
    at /usr/local/lib/node_modules/homebridge/src/server.ts:574:15
    at Array.forEach (<anonymous>)
    at Server.handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:554:17)
    at HomebridgeAPI.emit (events.js:310:20)
    at HomebridgeAPI.publishExternalAccessories (/usr/local/lib/node_modules/homebridge/src/api.ts:302:10)
    at RokuTvPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-roku-tv-plugin/src/roku-tv-platform.ts:78:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by BlueBeedle** [comment]
I have this issue as well. The TVs are named differently, but it only sees one and then the second TV shows as No Response in the home app.

**Comment by slvrscoobie** [comment]
same issue here, two TVs, named differently. I was able to add them yesterday, but this morning the bedroom TV says unresponsive. I tried to delete and readd but now its disappeared even though homebridge registers the two tv IPs. 
[7/7/2020, 9:35:55 AM] Homebridge is running on port 51421.
[7/7/2020, 9:36:01 AM] [RokuTV] Roku Tv Ip is: http://192.168.44.123:8060
[7/7/2020, 9:36:01 AM] [RokuTV] Adding Input FandangoNOW Movies & TV with info ID: 48607027, TYPE: menu
[7/7/2020, 9:36:01 AM] [RokuTV] Adding Input Cable box with info ID: 1295095989, TYPE: tvin
[7/7/2020, 9:36:01 AM] [RokuTV] Adding Input DVD player with info ID: 1295095988, TYPE: tvin
[7/7/2020, 9:36:01 AM] [RokuTV] Adding Input Chromecast with info ID: 1295095987, TYPE: tvin
..
[7/7/2020, 9:36:01 AM] [RokuTV] Roku Tv Ip is: http://192.168.44.135:8060
[7/7/2020, 9:36:01 AM] [RokuTV] Adding Input FandangoNOW Movies & TV with info ID: 48607027, TYPE: menu
..
[7/7/2020, 9:36:01 AM] 55" TCL Roku TV is running on port 43298.
[7/7/2020, 9:36:01 AM] Please add [55" TCL Roku TV] manually in Home app. Setup Code: 280-90-589

**Comment by fratinize** [comment]
Pretty much same thing here I have 4 Roku/tcl and one Roku express. Only my 2 largest tcl have been found. ( I have had to restart homebridge for other reasons) but only one shows as available the other not responding, restart will show only one as active
There are three other Roku plugins each has a good quality this one I really like 
love to see all my Rokus 
please let me know if I can supply some logs

**Comment by Travisco29** [comment]
It seems like he has given up on getting multiple to work.

**Comment by fratinize** [comment]
It does seem he has given up unless he has gotten tremendously busy

**Comment by Travisco29** [comment]
yeah. its prob pretty difficult to code for multiple tvs when you only have
1

**Comment by fratinize** [comment]
Happy to lend some logs 😀

**Comment by slvrscoobie** [comment]
same here :) living room and bedroom and i can only access one, which one
depends on whos awake when Home bridge reboots lol

**Comment by raygan** [comment]
I’m having this same issue, but when homebridge reboots it switches from my TCL Roku TV to a Roku stick I have on another TV, which I wasn’t even trying to use in Homebridge. It would be nice to be able to specify an IP address or something to lock it to a particular Roku.
