### ISSUE TITLE
Lot of error while TV in sleep mode

### ISSUE THREAD

**Issue by Damien514** [JarekToro/homebridge-roku-tv#9]
I found a lot of errors in my log file this morning. Not sure of the importance, but it seemed to be related with my TV going into sleep mode.

`
(node:1916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2337)
(node:1916) UnhandledPromiseRejectionWarning: FetchError: request to http://10.0.0.31:8060/query/device-info failed, reason: connect ETIMEDOUT 10.0.0.31:8060
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-roku-tv-plugin/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

If I restart Homebridge, I got this alert:

`[5/26/2020, 07:03:24] [Télévision] Error: Could not find any Roku devices after 10 seconds
    at RokuFinder.<anonymous> (/usr/lib/node_modules/homebridge-roku-tv-plugin/node_modules/roku-client/dist/discover.js:129:24)
    at RokuFinder.emit (events.js:310:20)
    at Timeout.done (/usr/lib/node_modules/homebridge-roku-tv-plugin/node_modules/roku-client/dist/discover.js:61:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

I have to turn on my TV and restart Homebridge to ge back to normal.

I think that it might be related with the TV cutting the WiFi connection when in sleep mode or something like that.

**Comment by JarekToro** [comment]
Correct my code should handle the errors better and not error out like that.

 but for best compatibility you can turn on “fast start” in the tv settings the the plugin will be able to connect even when it’s off and can turn the tv back on.

**Comment by Damien514** [comment]
Thanks for the great work, giving it a try.

**Comment by donavanbecker** [comment]
@JarekToro does this look like the same error?
[homebridge.log](https://github.com/JarekToro/homebridge-roku-tv/files/4885277/homebridge.log)
